server:
  port: 8006
  tomcat:
    uri-encoding: utf-8
eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka:cloud-eureka@localhost:8761/eureka/
  instance:
    #eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例 默认90s（开发环境)
    lease-expiration-duration-in-seconds: 10
    #eureka客户端需要向eureka服务器发送心跳的频率 默认30s （开发环境)
    lease-renewal-interval-in-seconds: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  messages:
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/zbzbzzz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      #初始化大小
      initial-size: 5
      max-active: 100
      min-idle: 5
      #获取连接等待超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
        #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时检测连接是否有效
      test-on-borrow: false
      #归还连接时检测连接是否有效
      test-on-return: false
      #打开PSCache,并且指定每个连接上的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        #配置StatFilter
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
          #配置WallFilter
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  application:
    name: user-service
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  mapper-locations: classpath:com/zbzbzzz/user/mapper/*.xml
  type-aliases-package: com.zbzbzzz.user.entity
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


swagger:
  enabled: true
  title: zbzbzzz-cloud
  description: 描述
  version: 版本
  license: 许可证
  licenseUrl: 许可证URL
  termsOfServiceUrl: 服务条款URL
  contact:
    name: zbzbzzz
    url: 维护人URL
    email: 维护人email
#  - swagger.base-package=swagger扫描的基础包，默认：全扫描
#  - swagger.base-path=需要处理的基础URL规则，默认：/**
#  - swagger.exclude-path=需要排除的URL规则，默认：空
#  - swagger.host=文档的host信息，默认：空
#  - swagger.globalOperationParameters[0].name=参数名
#  - swagger.globalOperationParameters[0].description=描述信息
#  - swagger.globalOperationParameters[0].modelRef=指定参数类型
#  - swagger.globalOperationParameters[0].parameterType=指定参数存放位置,可选header,query,path,body.form
#  - swagger.globalOperationParameters[0].required=指定参数是否必传，true,false
