server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka:cloud-eureka@localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/java-aodeng/hope-cloud/     # 配置git仓库的地址
          default-label: dev                                #配置文件分支
          search-paths: config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
